server:
  mode: "debug"
  port: ":9999"
  secret: "!QASEE%^TGFVB&"
  ssl:
    privatekey: "cert/server.key"
    cert: "cert/server.crt"
  trusted_proxies:
    - "172.40.20.14" # HAproxy A
    - "172.40.20.15" # HAproxy B
  cros:
    allowOrigins:
      - "https://127.0.0.1"
      - "https://localhost"
      - "https://127.0.0.1:5173"
      - "https://localhost:5173"
      - "https://dev.basi-a.top"
    allowCredentials: true
  mail:
    senderMail: "3188765573@qq.com"
    smtpServer: "smtp.qq.com"
    port: 465
    username: "basi-a@foxmail.com"
    password: "azldfqilnmimdgic"
    template: "template/emailTemplate.html"
  admin:
    useradmin:
      username: "useradmin"
      password: "123456hello"
      email: "3188765573@qq.com"
    s3admin:
      username: "s3admin"
      password: "123456hello"
      email: "basi-a@outlook.com"
  
redis:
  redisAddr: "127.0.0.1"
  redisPort: "16379"
  redisPassword: "TGVG8791HUBH"
  redisPoolConns: 2048

database:
  dbselect: "pgsql"
  mariadb:
    dbUsername:
    dbPassword:
    dbHost:
    dbPort:
    dbName:
    timeout:
    dbPoolConns:
  pgsql:
    dbUsername: "odisk"
    dbPassword: "FTVGBUY7uvib89Y"
    dbHost: "127.0.0.1"
    dbPort: "15432"
    dbName: "odisk"
    sslmode: "disable"
    timezone: "Asia/Shanghai"
    dbPoolConns: 2048

minio:
  endpoint: "172.40.20.100:9000"
  accessKeyID: "minioadmin"
  secretAccessKey: "minioadmin"
  usessl: true
  bucketName: "odisk"
  location: "zh-private-1"
  bucketMaxSize: 512 # 单位是GB
nsq:
  port:
    nsqlookupd:
      tcp: "4160"
      http: "4161"
    nsqd:
      tcp: "4150"
      http: "4151"
  nsqlookupd:
    - "172.40.20.24"
  nsqd: "172.40.20.25"
  topics:
    email:
      - user-auth
