server:
  mode: "debug"
  port: ":9999"
  secret: "!QASEE%^TGFVB&"
  ssl:
    privatekey: "cert/server.key"
    cert: "cert/server.crt"
  trusted_proxies:
    - "172.40.20.14" # HAproxy A
    - "172.40.20.15" # HAproxy B
  cros: 
    allowOrigins:
      - "https://127.0.0.1"
      - "https://localhost"
      - "https://dev.basi-a.top"
    allowCredentials: true
  mail:
    sender-mail: "basi1024@163.com"
    smtp-server: "smtp.example.com"
    port: 25
    username: "basi1024@163.com"
    password: "asgasga"
    template: "template/emailTemplate.html"
  admin:
    useradmin: 
      username: "useradmin"
      password: "123456hello"
      email:    "useradmin@example.com"
    s3admin:
      username: "s3admin"
      password: "123456hello"
      email:    "s3admin@example.com"

redis:
  redisAddr: "127.0.0.1"
  redisPort: "16379"
  redisPassword: "TGVG8791HUBH"
  redisPoolConns: 2048


database:
  dbselect: "pgsql"
  mariadb:
    dbUsername: 
    dbPassword: 
    dbHost: 
    dbPort: 
    dbName: 
    timeout:
    dbPoolConns: 
  pgsql:
    dbUsername: "odisk"
    dbPassword: "FTVGBUY7uvib89Y"
    dbHost: "127.0.0.1"
    dbPort: "15432"
    dbName: "odisk"
    sslmode: "disable"
    timezone: "Asia/Shanghai"
    dbPoolConns: 2048

minio:
  endpoint: "172.40.20.16:9000"
  accessKeyID: "minioadmin" 
  secretAccessKey: "minioadmin"
  usessl: false
  bucketName: "odisk"
  location: "zh-private-1"

nsq:
  nsqlookupd:
    - "172.40.20.24:4161"
    - "172.40.20.25:4161"
  nsqd:
    - "172.40.20.26:4150"
    - "172.40.20.27:4150"
    - "172.40.20.28:4150"
  nsqadmin:
    - "172.40.20.29:4171"
