# server
mode: "debug"
port: ":9999"
secret: "!QASEE%^TGFVB&"

# redis
redisAddr: "127.0.0.1"
redisPort: "16379"
redisPassword: "TGVG8791HUBH"

# mariadb
dbUsername: "odisk"
dbPassword: "FTVGBUY7uvib89Y"
dbHost: "127.0.0.1"
dbPort: "13306"
dbName: "odisk"
timeout: "10s"