server:
  mode: "debug"
  port: ":9999"
  secret: "!QASEE%^TGFVB&"
  ssl:
    privatekey: "cert/server.key"
    cert: "cert/server.crt"
  trusted_proxies:
    - "172.40.20.14" # HAproxy A
    - "172.40.20.15" # HAproxy B
  cros: 
    allowOrigins:
      - "https://127.0.0.1"
      - "https://localhost"
      - "https://xxxx.example.xyz"
    allowCredentials: true
    
  mail:
    sender-mail: "basi1024@163.com"
    smtp-server: "smtp.example.com"
    port: 25
    username: "basi1024@163.com"
    password: "asgasga"
    
redis:
  redisAddr: "127.0.0.1"
  redisPort: "16379"
  redisPassword: "TGVG8791HUBH"
  redisPoolConns: 2048

mariadb:
  dbUsername: "odisk"
  dbPassword: "FTVGBUY7uvib89Y"
  dbHost: "127.0.0.1"
  dbPort: "13306"
  dbName: "odisk"
  timeout: "10s"
  dbPoolConns: 2048

minio:
  endpoint: "172.40.20.16:9000"
  accessKeyID: "minioadmin" 
  secretAccessKey: "minioadmin"
  usessl: false
  bucketName: "odisk"
  location: "zh-private-1"