server:
  mode: "release"
  port: ":7000"
  secret: "!QASEE%^TGFVB&"
  trusted_proxies:
    - "keepalived_haproxy1"
    - "keepalived_haproxy2"
redis:
  redisAddr: "redis"
  redisPort: "6379"
  redisPassword: "TGVG8791HUBH"
  redisPoolConns: 100

mariadb:
  dbUsername: "odisk"
  dbPassword: "FTVGBUY7uvib89Y"
  dbHost: "mariadb"
  dbPort: "3306"
  dbName: "odisk"
  timeout: "10s"
  dbPoolConns: 100

minio:
  endpoint: "keepalived.vip:9000"
  accessKeyID: "minioadmin" 
  secretAccessKey: "minioadmin"
  usessl: false
  bucketName: "odisk"
  location: "zh-private-1"