server:
  mode: "release"
  port: ":7000"
  secret: "!QASEE%^TGFVB&"
  ssl:
    privatekey: "/opt/cert/server.key"
    cert: "/opt/cert/server.crt"
  trusted_proxies:
    - "keepalived_haproxy1"
    - "keepalived_haproxy2"
  mail:
    senderMail: "3188765573@qq.com"
    smtpServer: "smtp.qq.com"
    port: 465
    username: "3188765573@qq.com"
    password: "azldfqilnmimdgic"
    template: "/opt/template/emailTemplate.html"
  cros:
    allowOrigins:
      - "https://127.0.0.1"
      - "https://localhost"
      - "https://dev.basi-a.top"
    allowCredentials: true
  admin:
    useradmin:
      username: "useradmin"
      password: "123456hello"
      email: "useradmin@example.com"
    s3admin:
      username: "s3admin"
      password: "123456hello"
      email: "s3admin@example.com"

redis:
  redisAddr: "redis"
  redisPort: "6379"
  redisPassword: "TGVG8791HUBH"
  redisPoolConns: 100

database:
  dbselect: "pgsql"
  mariadb:
    dbUsername:
    dbPassword:
    dbHost:
    dbPort:
    dbName:
    timeout:
    dbPoolConns:
  pgsql:
    dbUsername: "odisk"
    dbPassword: "FTVGBUY7uvib89Y"
    dbHost: "db"
    dbPort: "5432"
    dbName: "odisk"
    sslmode: "disable"
    timezone: "Asia/Shanghai"
    dbPoolConns: 2048

minio:
  endpoint: "keepalived.vip:9000"
  accessKeyID: "minioadmin"
  secretAccessKey: "minioadmin"
  usessl: false
  bucketName: "odisk"
  location: "zh-private-1"

nsq:
  port:
    nsqlookupd:
      tcp: "4160"
      http: "4161"
    nsqd:
      tcp: "4150"
      http: "4151"
  nsqlookupd:
    - "nsqlookupd"
  nsqd: "nsqd"
  topics:
    email:
      - user-auth
